---
dist: xenial
language: node_js
node_js:
  - '10'
  - '12'

cache:
  directories:
    - /home/travis/.npm

before_install:
  - touch package.json

install:
  - make install
  - make precompile

script:
  - travis/script.sh

env:
  global:
    - MAKEFLAGS=-j2

    # NPM_TOKEN (robertrossmann)
    - secure: NT36P0ZCA3ZBrU7puGGJAi5C7KCmPL1vvgJXbW8HjOdWFvNw81MIETdxeXRTj4UHz/F9L6PmUwaDcm6UWHATHyydDaIrRkif3wORXGFfcAnRjNIvLPhtTTOl3KPInyWSxIY9rNu74BcH67U7t0r1aj8nqXsgi9ue8OouUc/Qw4ZMMgWDpO004ShuJjj4dTuL9+fcevc5pe6T1F1xGd3EoUzW6yKXYf659yXvrK3J4hGHYGb/vtmuKVb5dmTUTniWSC3IKXBJ6jd0M5Uct4Vm199vJGRiUhFeiADkoqYwnuX4JVDpYr3Tzu8PGz6DnGXZXshjSGpUJla37AaqzyeEpDom0ecOUhYiVFA+eugyKOMIMaOpUhnRnCh38Rhn/xspEvWqyGXCOB20ihIpRW8wkqUiK8SQMN4315r0uP7OCq+OwXkyJskJc3wv5qY2idJ3fT/X6Mt75CrmOw5v/R01oyQk+3sgYUtsnbva/5g9n3+TUHNvPq5Ar2obMOafDf4czrST0sV7HQXheU1ULevmIFp8RBtnyR0NhktYBEeSZZpc/QMGGdsZCU99AeHy8UFzFJZn+UtGSSpSmfLomnFHnKD53OwUebs7yZxiz9ft/dwTW8lT9Rg+XL909bDr3XuTtLDymrp8Q8k2eFlEJKjND5ARditPGGJazPwN40M1nE4=

deploy:
  skip_cleanup: true
  provider: script
  script: utils/release.sh
  on:
    repo: strvcom/heimdall
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/.{1,}$
    node: '12'
