---
name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: make install
      - run: make compile

      - name: ESLint
        run: make lint
      - name: Tests
        run: make test

  release:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    needs:
      - verify
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: make install
      - run: make compile
      - name: Publish to npm
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Post-release sync
        run: ./utils/ci/sync.sh
        if: success()
